---
permalink: san-host/concept_solaris_host_remediation.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, solaris, host, remediation 
summary: 'Si vous utilisez l"outil 7-mode transition Tool \(7MTT\) pour passer d"ONTAP sous 7-mode à clustered ONTAP dans un environnement SAN, vous devez effectuer une série d"étapes sur votre hôte Solaris avant et après la transition, afin d"éviter toute complication liée au processus de transition.' 
---
= Résolution des problèmes liés à l'hôte Solaris
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez l'outil 7-mode transition Tool (7MTT) pour passer d'un système ONTAP sous 7-mode à un système clustered ONTAP dans un environnement SAN, vous devez effectuer plusieurs étapes sur votre hôte Solaris avant et après la transition, afin d'éviter toute complication liée au processus de transition.

Les scénarios suivants ne sont pas pris en charge pour les flux de travail de transition (transitions basées sur la copie ou sans copie) :

* Transition des LUN de démarrage SAN
+
Vous pouvez configurer une LUN de démarrage SAN pour qu'elle fonctionne dans un environnement Veritas Dynamic Multipathing (DMP) ou dans un environnement Solaris MPxIO en exécutant Solaris Host Utilities et en utilisant le protocole FC. La méthode que vous utilisez pour configurer une LUN de démarrage SAN peut varier en fonction de votre gestionnaire de volumes et de votre système de fichiers.

+
https://["Solaris Host Utilities 6.2 - Guide d'installation et de configuration"]

* Transition vers la mise en cluster des hôtes Solaris
* Configuration Veritas

