---
permalink: san-host/concept_how_to_identify_vm_snapshots_that_must_be_removed_before_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, vm, snapshots, removed, identify 
summary: 'Snapshots de machines virtuelles \(VM\) avec Virtual RDM attaché ne survivent pas à la transition de Data ONTAP fonctionnant en 7-mode vers clustered Data ONTAP. Ces snapshots doivent être supprimés avant la transition. Les snapshots de machines virtuelles avec uniquement des disques virtuels VMFS et des RDM physiques \(PTRDM\) survivent à la transition et n"ont pas besoin d"être supprimés.' 
---
= Comment identifier les snapshots de machines virtuelles qui doivent être supprimés avant la transition
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La transition des machines virtuelles instantanées (VM) avec Virtual RDM attaché n'est pas en cours de transition de Data ONTAP fonctionnant en 7-mode vers clustered Data ONTAP. Ces snapshots doivent être supprimés avant la transition. Les snapshots de machines virtuelles avec uniquement des disques virtuels VMFS et des RDM physiques (PTRDM) survivent à la transition et n'ont pas besoin d'être supprimés.

Vous pouvez utiliser le classeur _Inventory Assessment Workbook_ généré par l'outil Inventory Collect Tool pour identifier toutes les machines virtuelles avec des RDM virtuels rattachés. Les instantanés répertoriés dans le classeur _Inventory Assessment Workbook_ sous la colonne snapshots de VM et la colonne NPTRDM avec une valeur supérieure à 0 sont des machines virtuelles dont un RDM virtuel est associé à des instantanés de VM.
