---
permalink: san-host/concept_preparing_for_cutover_when_transitioning_san_boot_luns.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, cutover, phase, san, boot, lun 
summary: Si vous migrez des LUN de démarrage SAN de Data ONTAP sous 7-mode vers clustered Data ONTAP, vous devez connaître certaines conditions préalables avant de passer à la phase de mise en service. 
---
= Préparation de la phase de mise en service lors de la transition des LUN de démarrage SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous migrez des LUN de démarrage SAN de Data ONTAP sous 7-mode vers clustered Data ONTAP, vous devez connaître certaines conditions préalables avant de passer à la phase de mise en service.

Vous devez disposer d'une connectivité et d'une segmentation de la structure à vos contrôleurs clustered Data ONTAP pour les configurations FC. Pour les configurations iSCSI, vos sessions iSCSI doivent être découvertes et connectées à vos contrôleurs clustered Data ONTAP. Vous devez également arrêter votre hôte.

* Pour les transitions basées sur la copie, vous devez arrêter l'hôte avant d'initier l'opération de mise en service du stockage dans l'outil de transition 7-mode (7MTT). Les transitions sans copie ne sont pas prises en charge sur les hôtes HP-UX.
* Pour les transitions sans copie, vous devez arrêter l'hôte avant de lancer l'opération 7-mode d'exportation et d'arrêt de l'outil 7MTT.

