---
permalink: san-host/concept_vmware_esxi_host_remediation.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, esxi, host, remediation 
summary: 'Si vous utilisez l"outil 7-mode transition Tool \ (7MTT\) pour passer d"un environnement Data ONTAP sous 7-mode à un système clustered Data ONTAP dans un environnement SAN, vous devez effectuer une série d"étapes sur vos hôtes VMware ESXi avant la transition vers Data ONTAP. Vous devez arrêter vos hôtes avant la mise en service et effectuer une autre série d"étapes après la transition avant de pouvoir procéder à la maintenance des données.' 
---
= Résolution des problèmes liés à l'hôte VMware ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez l'outil 7-mode transition Tool (7MTT) pour passer d'un environnement Data ONTAP sous 7-mode à un environnement clustered Data ONTAP dans un environnement SAN, vous devez effectuer plusieurs étapes sur vos hôtes VMware ESXi avant la transition Data ONTAP. Vous devez arrêter vos hôtes avant la mise en service et effectuer une autre série d'étapes après la transition avant de pouvoir procéder à la maintenance des données.

*Informations connexes*

xref:task_testing_transitioned_luns_and_esxi_host_applications_before_cutover.adoc[Le test des LUN migrées et des applications hôte ESXi avant la phase de mise en service des transitions basées sur la copie]

xref:concept_post_transition_requirements_for_esxi_hosts.adoc[Exigences de correction post-transition pour les hôtes ESXi]
