---
permalink: san-host/concept_esxi_versions_and_features_supported_for_san_transitions_using_7mtt.html 
sidebar: sidebar 
keywords: esxi, ontap, san, host, transition, versions, san, 7mtt, features 
summary: 'Seules certaines versions et fonctionnalités de ESXi sont prises en charge pour les transitions SAN à l"aide de l"outil 7-mode transition Tool \(7MTT\).' 
---
= Versions et fonctionnalités ESXi prises en charge pour les transitions SAN à l'aide de 7MTT
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seules les versions et fonctionnalités de ESXi sont prises en charge pour les transitions SAN à l'aide de l'outil 7-mode transition Tool (7MTT).

Les versions et fonctionnalités suivantes sont prises en charge comme indiqué dans le link:https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"]

* ESXi 5.0, 5.1, 5.5 et versions ultérieures
+
Vous devez mettre à niveau les hôtes exécutant ESX/ESXi 4.x ou une version antérieure vers ESX/ESXi 5.0 ou une version ultérieure pour pouvoir les migrer.

* Datastores VMFS3 et VMFS5
* Configurations de démarrage SAN
* Périphériques RDM (RAW device map)
* Tous les systèmes d'exploitation invités sont pris en charge par la matrice d'interopérabilité
* Tous les protocoles SAN (FC/FCoE/iSCSI)

