---
permalink: san-host/concept_exceptions_and_known_issues_when_transitioning_san_hosts_to_clustered_ontap.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, exceptions, issues, san, host 
summary: 'Notez certaines exceptions et certains problèmes connus lors de la transition des hôtes SAN de Data ONTAP fonctionnant sous 7-mode vers des versions ultérieures d"ONTAP.' 
---
= Exceptions et problèmes connus lors de la transition d'hôtes SAN vers ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Notez certaines exceptions et certains problèmes connus lors de la transition des hôtes SAN de Data ONTAP fonctionnant sous 7-mode vers des versions ultérieures d'ONTAP.

* Pour la transition d'Hyper-Virtual machine (machines virtuelles) avec uniquement des types de fichiers VHD ou VHDX, vous pouvez utiliser la migration dynamique du stockage au lieu de l'outil 7-mode transition Tool (7MTT).
+
Pour plus d'informations sur la migration dynamique du stockage Hyper-V, consultez la documentation Microsoft.

* Si vous utilisez le même nom de groupe initiateur sur les deux nœuds du contrôleur 7-mode, l'outil de transition risque de ne pas pouvoir résoudre le conflit entre ce groupe initiateur.
+
ID de bug https://["769715"].


