---
permalink: san-host/task_mounting_logical_volumes_on_linux_host_after_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, mount, logical, volumes, linux, hosts 
summary: Après la transition de ONTAP 7-mode vers clustered Data ONTAP, vos volumes logiques sont hors ligne. Vous devez monter ces volumes logiques pour que vos LUN soient accessibles à vos hôtes. 
---
= Montage de volumes logiques sur des hôtes Linux après la transition
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après la transition de ONTAP 7-mode vers clustered Data ONTAP, vos volumes logiques sont hors ligne. Vous devez monter ces volumes logiques pour que vos LUN soient accessibles à vos hôtes.

Pour une transition sans copie, les procédures de réhébergement de volumes doivent être complètes. Voir la link:https://docs.netapp.com/us-en/ontap-7mode-transition/copy-free/index.html["Guide de transition sans copie de l'outil 7-mode"] pour plus d'informations.

* Pour les transitions basées sur la copie, effectuez ces étapes après la mise en service du stockage dans l'outil 7-mode transition Tool (7MTT).
* Pour les CFT, effectuez ces étapes après l'opération Import Data & Configuration dans l'outil 7MTT.
+
.. Générer le fichier de mappage de LUN 7-mode vers clustered Data ONTAP :
+
*** Pour les transitions basées sur la copie, exécutez la commande suivante depuis l'hôte Linux sur lequel l'outil 7MTT est installé : +
`*transition cbt export lunmap -p _project-name_ -o _file_path_*`
+
Par exemple :

+
`*transition cbt export lunmap -p SanWorkLoad -o c:/Libraires/Documents/7-to-C-LUN-MAPPING.csv*`

*** Pour les transitions sans copie, exécutez la commande suivante depuis le système sur lequel l'outil 7MTT est installé :
+
`*transition cft export lunmap -p p_roject-name_ -s _svm-name_ -o _output-file_*`

+
Par exemple :

+
`*transition cft export lunmap -p SanWorkLoad -s svml -0 c:/Libraries/Documents/7-to-C-LUN-MAPPING-svml.csv*`

+

NOTE: Vous devez exécuter cette commande pour chaque SVM.



.. Supprimez les périphériques SCSI créés pour les LUN 7-mode :
+
*** Pour supprimer tous les périphériques SCSI : +
`*rescan-scsi-bus.sh -r*`
*** Pour retirer chaque périphérique SCSI individuellement : +
`*echo 1> /sys/block/__SCSI_ID__/delete*`
+
Cette commande doit être exécutée sur tous les périphériques SCSI LUN 7-mode. Consultez la colonne ID de périphérique SCSI de l'onglet LUN hôte SAN du Manuel d'évaluation d'inventaire_ pour identifier les ID de périphérique SCSI des LUN.



.. Découvrir les nouveaux LUN ONTAP :
+
`*rescan-scsi-bus.sh*`

.. Configuration des périphériques DMMP pour les LUN ONTAP :
+
`*multipath*`

.. Vérifiez que les LUN ONTAP sont découvertes :
+
`*sanlun lun show*`

.. Déterminez le nouvel ID de descripteur de périphérique LUN ONTAP :
+
`*multipath -ll _Device_handle_name_*`

.. Importer le groupe de volumes :
+
`*vgimport _vg_name_*`

.. Vérifiez l'état du groupe de volumes :
+
`*vgdisplay*`

.. Activer les volumes logiques :
+
`*vgchange -ay _vg_name_*`

.. Vérifiez l'état du volume logique :
+
`*lvdisplay*`

+
L'état du VG doit être affiché comme « disponible ».

.. Montez les volumes logiques depuis la LUN ONTAP vers le répertoire de point de montage respectif :
+
`mount _lv_namemount_point_`

+
Si les points de montage sont définis dans le `etc/fstab` fichier, vous pouvez utiliser `mount -a` commande de montage des volumes logiques.

.. Vérifiez les points de montage :
+
`*mount*`




