---
permalink: san-host/task_mounting_solaris_host_luns_with_sun_volume_manager_after_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, mount, solaris, host, lun, volume, manager 
summary: Après la transition des LUN hôte Solaris avec Solaris Volume Manager, de ONTAP 7-mode à clustered ONTAP, vous devez monter les LUN. 
---
= Montage des LUN hôtes Solaris avec Solaris Volume Manager après la transition
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après la transition des LUN hôte Solaris avec Solaris Volume Manager, de ONTAP 7-mode à clustered ONTAP, vous devez monter les LUN.

Pour les transitions basées sur les copies, effectuez ces étapes après la mise en service du stockage dans l'outil 7-mode transition Tool (7MTT).

Pour les transitions sans copie, effectuez cette procédure une fois que le processus Import Data & Configuration de l'outil 7MTT est terminé.

.Étapes
. Découvrez vos nouvelles LUN clustered ONTAP en réutilisant l'hôte.
+
.. Identifiez les ports hôtes FC (type fc-fabric) : +
`*#cfgadm _–l_*`
.. Déconfigurez le premier port fc-fabric : +
`*#cfgadm –c unconfigure _c1_*`
.. Déconfigurez le second port fc-fabric : +
`*#cfgadm –c unconfigure _c2_*`
.. Répétez les étapes pour les autres ports fc-fabric.
.. Vérifiez les ports hôte et leurs périphériques connectés : +
`*# cfgadm _–al_*`
.. Recharger le pilote : +
`*# devfsadm –Cv*`
+
`*# devfsadm –i iscsi*`



. Vérifiez que vos LUN clustered ONTAP ont été découvertes :
+
`*sanlun lun show*`

+
** Le `lun-pathname` Les valeurs des LUN clustered ONTAP doivent être identiques à celles du `lun-pathname` Valeurs des LUN 7-mode avant la transition.
** Le `mode` La colonne doit afficher « C » au lieu de « 7 ».


+
[listing]
----
# sanlun lun show
controller(7mode)/                    device                                            host                  lun
vserver(Cmode)       lun-pathname     filename                                          adapter    protocol   size    mode
--------------------------------------------------------------------------------------------------------------------------
vs_sru17_5           /vol/zfs/zfs2    /dev/rdsk/c5t600A0980383030444D2B466542485935d0s2 scsi_vhci0 FCP        6g      C
vs_sru17_5           /vol/zfs/zfs1    /dev/rdsk/c5t600A0980383030444D2B466542485934d0s2 scsi_vhci0 FCP        6g      C
vs_sru17_5           /vol/ufs/ufs2    /dev/rdsk/c5t600A0980383030444D2B466542485937d0s2 scsi_vhci0 FCP        5g      C
vs_sru17_5           /vol/ufs/ufs1    /dev/rdsk/c5t600A0980383030444D2B466542485936d0s2 scsi_vhci0 FCP        5g      C
----
. Importez des jeux de disques dans des configurations Solaris Volume Manager existantes, en utilisant le même nom de jeu de disques :
+
`*metaimport -s _set-name_*`

+
[listing]
----
# metaimport -s svm
Drives in regular diskset including disk c0t60A98000383035356C2447384D39654Ad0:
  c0t60A98000383035356C2447384D39654Ad0
  c0t60A98000383035356C2447384D396548d0
More info:
  metaimport -r -v c0t60A98000383035356C2447384D39654Ad0

# metastat -s svm
svm/d2: Concat/Stripe
    Size: 10452992 blocks (5.0 GB)
    Stripe 0:
        Device                                             Start Block  Dbase   Reloc
        /dev/dsk/c0t60A98000383035356C2447384D396548d0s0          0     No      Yes

svm/d1: Concat/Stripe
    Size: 10452992 blocks (5.0 GB)
    Stripe 0:
        Device                                             Start Block  Dbase   Reloc
        /dev/dsk/c0t60A98000383035356C2447384D39654Ad0s0          0     No      Yes

Device Relocation Information:
Device                                           Reloc  Device ID
/dev/dsk/c0t60A98000383035356C2447384D396548d0   Yes    id1,sd@n60a98000383035356c2447384d396548
/dev/dsk/c0t60A98000383035356C2447384D39654Ad0   Yes    id1,sd@n60a98000383035356c2447384d39654a
----
. Exécuter la vérification du système de fichiers :
+
`*fsck -F ufs /dev/md/svm/rdsk/d1*`

+
[listing]
----
# fsck -F ufs /dev/md/svm/rdsk/d1
** /dev/md/svm/rdsk/d1
** Last Mounted on /d1
** Phase 1 - Check Blocks and Sizes
** Phase 2 - Check Pathnames
** Phase 3a - Check Connectivity
** Phase 3b - Verify Shadows/ACLs
** Phase 4 - Check Reference Counts
** Phase 5 - Check Cylinder Groups
3 files, 1573649 used, 3568109 free (13 frags, 446012 blocks, 0.0% fragmentation)
----
. Montez manuellement chacun des périphériques à l'aide du `mount` commande.
+
[listing]
----
# /sbin/mount -F ufs -o largefiles /dev/md/svm/dsk/d1  /d1
  # /sbin/mount -F ufs -o largefiles /dev/md/svm/dsk/d2  /d2
----
. Vérifiez le point de montage :
+
`*df -ah*`


