---
permalink: san-host/task_making_san_boot_lun_primary_boot_lun_for_hp_ux_qlogic_hbas_after_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, boot, lun, primary, hp, ux, logic, hbas 
summary: Si le SAN de votre système Data ONTAP fonctionnant sous 7-mode HP-UX a démarré, vous devez faire du LUN de démarrage SAN le LUN de démarrage principal après la transition vers clustered Data ONTAP. 
---
= La création d'une LUN de démarrage SAN est la LUN de démarrage principale pour les HBA QLogic HP-UX après la transition
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si le SAN de votre système Data ONTAP fonctionnant sous 7-mode HP-UX a démarré, vous devez faire du LUN de démarrage SAN le LUN de démarrage principal après la transition vers clustered Data ONTAP.

* La migration des données doit être terminée.
* Votre LUN de démarrage doit être mappée sur votre hôte depuis votre nœud clustered Data ONTAP.


LE démarrage SAN est pris en charge pour HP-UX 11.3x sur les systèmes HP 9000 à l'aide du menu BCH et sur les serveurs HP Integrity utilisant le chargeur HP-UX (EFI).

Pour les transitions basées sur les copies, effectuez ces étapes après la mise en service du stockage dans l'outil de transition 7-mode. Les transitions sans copie ne sont pas prises en charge sur les hôtes HP-UX.

.Étapes
. Ouvrez l'invite du shell :
+
`*Ctrl B*`

. Démarrez à partir du shell EFI.
+
Le shell EFI est disponible uniquement sur les systèmes HP Integrity.

. Utilisez une console série pour accéder à la connexion au processeur de service.
. Accéder à la liste des consoles : `CO`
+
Le menu du Gestionnaire de démarrage EFI s'ouvre.

. Dans le menu du Gestionnaire de démarrage EFI, sélectionnez l'option de menu shell EFI pour accéder à l'environnement shell EFI.
. Identifiez les numéros de pilotes QLogic :
+
`*drivers*`

+
Les numéros de conducteur se trouvent dans la colonne DRV.

. Identifiez le numéro de contrôleur correspondant pour chaque pilote :
+
`*drvcfg _driver_number_*`

+
Dans l'exemple suivant : `27` est le numéro de contrôleur correspondant pour le pilote `23` et `26` est le numéro de contrôleur correspondant pour le pilote `24`:

+
[listing]
----
Shell> drvcfg 23
Configurable Components
		Drv[23]		Ctrl[27]			Lang[eng]

Shell> drvcfg 24
Configurable Components
		Drv[24]		Ctrl[26]			Lang[eng]
----
. Ouvrez le BIOS du pilote :
+
`*drvcfg _drv_number ctrl_number_ -s*`

. Entrez `*4*` pour sélectionner *4. Modifier les paramètres de démarrage*.
. Dans Modifier les paramètres de démarrage, entrez `6` pour sélectionner *6. Variable EFI EFIFCScanLevel*.
. Entrez `*1*` Pour modifier la valeur de la variable EFI EFIFCScanLevel de 0 à 1.
. Entrez `*7*` pour sélectionner *7. Activer la connexion mondiale*.
. Entrez `*y*` pour activer la connexion world.
. Entrez `*0*` pour accéder au menu précédent.
. Dans le menu principal, entrez `*11*` pour enregistrer vos modifications.
. Entrez `*12*` pour quitter.
. Dans l'invite du shell, relancez l'analyse de vos périphériques :
+
`*reconnect -r*`

. Affichez la LUN pour obtenir le chemin d'accès à la LUN à partir de laquelle vous souhaitez démarrer :
+
`*map -r*`

+
Les chemins de LUN sont répertoriés dans la colonne périphérique. Le disque SAN amorçable est affiché sous la colonne table de mappage et a « WWN » et « partie 1 » dans la chaîne de sortie.

. Indiquez le chemin d'accès LUN de votre LUN de démarrage SAN.
+
Un exemple de chemin de LUN est fs0.

. Quittez le shell EFI :
+
`*cd efi*`

. Entrez le répertoire HPUX :
+
`*cd hpux*`

. Faites du nouveau LUN de démarrage SAN clustered Data ONTAP le LUN de démarrage principal :
+
`*bcfg boot add 1 hpux.efi "HP-UX-Primary Boot"*`

. Mettez manuellement à jour le BIOS du HBA en créant une entrée dans EFI pour le LUN de démarrage du SAN.
. Créez un chemin de démarrage alternatif :
+
`*bcfg boot add 2 hpux.efi “HPUX alternate boot”*`

. Créer un troisième chemin de démarrage :
+
`*bcfg boot add 2 hpux.efi “HPUX third boot”*`

. Créez un quatrième chemin d'amorçage :
+
`*bcfg boot add 2 hpux.efi “HPUX fourth boot”*`


