---
permalink: san-host/task_enabling_caw_on_a_datastore_using_esxi_cli.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, enable, caw, datastore, esxi, cli 
summary: 'Si vous ne disposez pas de la prise en charge de Comparer et d"écrire \(CAW\) dans Data ONTAP fonctionnant en 7-mode, vous devez activer manuellement la prise en charge de CAW lors de la transition vers clustered Data ONTAP. Clustered Data ONTAP supporte CAW par défaut.' 
---
= Activation de CAW sur un datastore à l'aide de la CLI ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous ne aviez pas pris en charge la fonction Comparer et écrire (CAW) dans Data ONTAP fonctionnant en 7-mode, vous devez activer manuellement la prise en charge de CAW lors de la transition vers clustered Data ONTAP. Clustered Data ONTAP supporte CAW par défaut.

* Il ne doit y avoir aucune E/S ou machine virtuelle active sur le datastore VMFS.
* Le datastore doit être remonté si le datastore a été migré.
* Le nouveau ONTAP LUN naa doit être utilisé dans le fichier de mappage 7-mode transition Tool (7MTT).


CAW doit être activé uniquement lorsqu'aucune E/S ou VM n'est en cours d'exécution sur le datastore VMFS.

* CAW doit être activé uniquement lorsqu'aucune E/S ou VM n'est en cours d'exécution sur le datastore VMFS.
* Pour les transitions basées sur la copie, effectuez ces étapes après la mise en service du stockage dans 7MTT.
* Pour les transitions sans copie, effectuez ces étapes une fois l'opération Import Data & Configuration terminée dans 7MTT.


.Étapes
. Ouvrez le classeur _Inventory Assessment Workbook_ généré par l'outil Inventory Collect Tool (ICT).
. Accédez à l'onglet systèmes de fichiers hôtes SAN.
. Vérifiez l'état CAW du datastore.
+
La valeur *ATS/CAW* du datastore doit afficher *Disabled* et la colonne Filesystem doit afficher *VMFS.x*.

. Notez le nom du datastore dans la colonne disque
. Connectez-vous à la console ESXi à l'aide de SSH.
. Lister les informations sur le périphérique et la partition :
+
`*~ # vmkfstools -Ph -v1 _datastore_path_*`

+
Datastore_path est le nom du datastore dans la colonne disque du classeur _Inventory Assessment Workbook_.

+
`*# vmkfstools -Ph -v1 /vmfs/volumes/datastorename*`

+
[listing]
----
VMFS-5.60 file system spanning 1 partitions.
File system label (if any): datastorename
Mode: public
Capacity 9.8 GB, 8.2 GB available, file block size 1 MB, max file size 64
TB
Volume Creation Time: Mon Dec 9 10:29:18 2013
Files (max/free): 27408/27394
Ptr Blocks (max/free): 64512/64495
Sub Blocks (max/free): 3968/3964
Secondary Ptr Blocks (max/free): 256/256
File Blocks (overcommit/used/overcommit %): 0/1593/0
Ptr Blocks (overcommit/used/overcommit %): 0/17/0
Sub Blocks (overcommit/used/overcommit %): 0/4/0
Volume Metadata size: 590675968
UUID: 52a59b7e-52d2fb6c-11d6-001ec9d631cb
Partitions spanned (on "lvm"):
naa.600a098044314c6c442b446d51376749:1
naa.600a098054314c6c445d446f79716431:1
naa.600a098054314c6c445d446f79716433:1
Is Native Snapshot Capable: YES
----
. Notez le premier nom de périphérique et le numéro de partition.
+
Dans l'exemple précédent, `naa.600a098044314c6c442b446d51376749:1` est le nom du périphérique et le numéro de la partition.

. Utilisez l'ID du périphérique et le numéro de partition pour activer CAW sur le datastore :
+
`*~# vmkfstools --configATSOnly 1 /vmfs/devices/disks/__device-ID:Partition__*`

. Vérifier que le volume VMFS a été configuré avec ATS uniquement :
+
`*# vmkfstools -Ph -v1 /vmfs/volumes/VMFS-volume-name*`

+
[listing]
----
VMFS-5.54 file system spanning 1 partitions.
File system label (if any): ats-test-1
Mode: public ATS-only
----


*Informations connexes*

xref:task_remounting_vmfs_volumes_after_transition_using_vsphere_client.adoc[Le remontage des volumes VMFS après la transition à l'aide du client vSphere]

xref:task_remounting_vmfs_volumes_after_transition_using_esxi_cli_console.adoc[Remontage des volumes VMFS après la transition à l'aide de la CLI ESXi]

https://pubs.vmware.com/vsphere-55/index.jsp?topic=/com.vmware.vsphere.storage.doc/GUID-6887003D-2322-49AC-A56C-7AFE7350DB5D.html["Documentation VMware"]
