---
permalink: san-host/task_testing_transitioned_san_boot_luns_on_aix_hosts_before_cutover.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, boot, lun, aix, hosts, cutover, phase, copy, based 
summary: 'Si vous utilisez l"outil 7-mode transition Tool \ (7MTT\) 2.2 ou une version ultérieure et Data ONTAP 8.3.2 ou une version ultérieure pour effectuer la transition de vos LUN hôtes 7-mode Windows, vous pouvez tester vos LUN clustered Data ONTAP migrées avant la phase de mise en service pour vérifier qu"ils fonctionnent comme vous le souhaitez.' 
---
= Le test a effectué la transition de LUN de démarrage SAN sur des hôtes AIX avant la phase de mise en service des transitions basées sur la copie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez l'outil 7-mode transition Tool (7MTT) 2.2 ou une version ultérieure et Data ONTAP 8.3.2 ou une version ultérieure pour effectuer la transition de vos LUN hôtes 7-mode Windows, vous pouvez tester les LUN clustered Data ONTAP migrées avant la phase de mise en service pour vérifier qu'ils fonctionnent comme vous le souhaitez.

Vos LUN 7-mode doivent être prêts pour la transition.

Vous devez maintenir la parité matérielle entre l'hôte de test et l'hôte source, et vous devez effectuer les étapes suivantes sur l'hôte de test.

Vos LUN clustered Data ONTAP sont en mode lecture/écriture pendant le test. Ils se convertissent en mode lecture seule une fois le test terminé et que vous préparez la phase de mise en service.

.Étapes
. Une fois la copie des données de base terminée, sélectionnez *Test mode* dans l'interface utilisateur 7MTT.
. Dans l'interface utilisateur 7MTT, cliquez sur *Apply Configuration*.
. Sur l'hôte de test, connectez-vous à la console de gestion du matériel, puis démarrez votre hôte dans le menu *SMS*.
. Une fois l'hôte démarré, modifiez l'adresse IP et le nom d'hôte.
. Vérifiez que vos LUN clustered Data ONTAP sont présentes :
+
`*sanlun lun show*`

. Effectuez les tests selon les besoins.
. Arrêtez l'hôte de test :
+
`*shutdown -h*`

. Dans l'interface utilisateur 7MTT, cliquez sur *Finish Testing*.


Si vos LUN clustered Data ONTAP doivent être remappées sur votre hôte source, vous devez préparer l'hôte source à la phase de mise en service. Si vos LUN clustered Data ONTAP doivent rester mappées sur l'hôte de test, aucune étape supplémentaire n'est requise sur l'hôte de test.
