---
permalink: san-host/task_preparing_to_transition_san_boot_luns_on_aix_hosts_with_fc_fcoe_configurations.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, san, boot, lun, aix, host, fc, fcoe 
summary: 'Avant de procéder à la transition d"une LUN de démarrage SAN sur un hôte AIX avec une configuration FC/FCoE, vous devez enregistrer le nom de l"LUN 7-mode sur lequel AIX est installé et le nom du périphérique SCSI pour cette LUN.' 
---
= Préparation à la transition des LUN de démarrage SAN sur des hôtes AIX avec des configurations FC/FCoE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de procéder à la transition d'une LUN de démarrage SAN sur un hôte AIX avec une configuration FC/FCoE, vous devez enregistrer le nom de l'LUN 7-mode sur lequel AIX est installé et le nom du périphérique SCSI pour cette LUN.

. Dans la console de votre contrôleur Data ONTAP 7-mode, identifiez le nom de LUN 7-mode sur lequel AIX 7.1 et AIX 6.1 sont installés :
+
`*lun show*`

. Procurez-vous le nom de périphérique SCSI pour la LUN sur l'hôte :
+
`*sanlun lun show*`

+
Dans l'exemple suivant, la LUN de transition est `lun_sanboot_fas3170_aix04` Et le périphérique SCSI pour cette LUN est `hdisk0`.

+
[listing]
----
[04:02 AM root@822-aix03p1/]: sanlun lun show
controller[7mode]/
vserver[Cmode] lun-pathname
---------------------------------------------------------------------
fas3170-aix04  /vol/vol_fas3170_aix04_sanboot/lun_sanboot_fas3170_aix04
kit            /vol/kit/kit_0
kit            /vol/kit/kit_0
filename	adapter	protocol	size		mode
-------------------------------------
hdisk0     fcs0       FCP      100g	  7
hdisk1     fcs0       FCP      5g       C
hdisk2     fcs0       FCP      5g       C
----

