---
permalink: san-host/task_preparing_to_transition_san_boot_luns_on_hp_ux_hosts_with_fc_configurations.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, hp, ux, hosts, fc, configurations 
summary: 'Avant de procéder à la transition d"une LUN de démarrage SAN sur un hôte HP-UX avec une configuration FC, vous devez enregistrer le nom du LUN 7-mode sur lequel HP-UX est installé, le nom du périphérique SCSI pour cette LUN, la convention de nommage agile et le WWID.' 
---
= Préparation de la transition des LUN de démarrage SAN sur des hôtes HP-UX avec configurations FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de procéder à la transition d'une LUN de démarrage SAN sur un hôte HP-UX avec une configuration FC, vous devez enregistrer le nom du LUN 7-mode sur lequel HP-UX est installé, le nom du périphérique SCSI pour cette LUN, la convention de nommage agile et le WWID.

. Depuis la console du contrôleur 7-mode, affichez vos LUN 7-mode afin d'identifier le nom de LUN sur lequel est installé le système d'exploitation « HPUX11v3 Mars 2014 » :
+
`*lun show*`

. Obtenez le nom du périphérique SCSI pour la LUN :
+
`*sanlun lun show -p*`

+
Dans cet exemple, le LUN de transition est bootlun_94. Les périphériques SCSI pour cette LUN sont `/dev/dsk/c14t0d0`, `/dev/dsk/c27t0d0`, `/dev/dsk/c40t0d0`, et `/dev/dsk/c31t0d0` .

+
[listing]
----
        ONTAP Path: f8040-211-183:/vol/vol_183/bootlun_94
               LUN: 0
          LUN Size: 100g
       Host Device: /dev/rdisk/disk6
              Mode: 7
Multipath Provider: None
host      vserver   /dev/dsk
path      path      filename           host     vserver
state     type      or hardware path   adapter  LIF
-----     -------   ----------------   -------  -------
up        secondary /dev/dsk/c14t0d0   fcd0     fc4
up        primary   /dev/dsk/c27t0d0   fcd0     fc2
up        primary   /dev/dsk/c40t0d0   fcd1     fc1
up        secondary /dev/dsk/c31t0d0   fcd1     fc3
----
. Identifiez le WWID de la LUN sur l'hôte :
+
`*scsimgr get_info -D _SCSI_device_name_ |grep WWID*`

+
Dans l'exemple suivant, le WWID de LUN du périphérique `/dev/rdisk/disk6` est 0x600a09804d537739422445386b75556 :

+
[listing]
----
bash-2.05# scsimgr get_info -D /dev/rdisk/disk6 | grep WWID
World Wide Identifier (WWID)      = 0x600a09804d537739422445386b755564
bash-2.05#
----

