---
permalink: san-host/task_testing_transitioned_luns_on_aix_hosts_before_cutover.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, lun, aix, cutover, phase, copy, based, test 
summary: 'Si vous utilisez l"outil 7-mode transition Tool \(7MTT\) 2.2 ou une version ultérieure et Data ONTAP 8.3.2 ou une version ultérieure pour effectuer la transition de vos LUN hôtes AIX, vous pouvez tester les LUN clustered Data ONTAP migrées pour vous assurer que vous pouvez monter votre périphérique MPIO avant la phase de mise en service. Pendant le test, l"hôte source peut continuer à exécuter les E/S sur les LUN 7-mode source.' 
---
= Le test a effectué la transition de LUN sur des hôtes AIX avant la phase de mise en service des transitions basées sur la copie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez l'outil 7-mode transition Tool (7MTT) 2.2 ou une version ultérieure et Data ONTAP 8.3.2 ou une version ultérieure pour effectuer la transition de vos LUN hôtes AIX, vous pouvez tester vos LUN clustered Data ONTAP migrées pour vérifier que vous pouvez monter votre périphérique MPIO avant la phase de mise en service. Pendant le test, l'hôte source peut continuer à exécuter les E/S sur les LUN 7-mode source.

Vos LUN doivent être prêtes pour la transition.

Vous devez maintenir la parité matérielle entre l'hôte de test et l'hôte source et effectuer les étapes suivantes sur l'hôte de test.

Vos LUN clustered Data ONTAP sont en mode lecture/écriture pendant le test. Ils se convertissent en mode lecture seule une fois le test terminé et que vous préparez la phase de mise en service.

.Étapes
. Une fois la copie de données de base terminée, sélectionnez *Test mode* dans l'interface utilisateur 7MTT.
. Dans l'interface utilisateur 7MTT, cliquez sur *Apply Configuration*.
. Sur l'hôte de test, relancez l'analyse de vos nouveaux LUN clustered Data ONTAP :
+
`*cfgmgr*`

. Vérifiez que vos nouvelles LUN clustered Data ONTAP sont présentes :
+
`*sanlun lun show*`

. Vérifiez l'état du groupe de volumes :
+
`*lsvg vg_name*`

. Montez chacun des volumes logiques :
+
`*mount -o log/dev/loglv00 _file_system_mount_point_*`

. Vérifiez les points de montage :
+
`*df*`

. Effectuez les tests selon les besoins.
. Arrêtez l'hôte de test :
+
`*shutdown -h*`

. Dans l'interface utilisateur 7MTT, cliquez sur *Finish Testing*.


Si vos LUN clustered Data ONTAP doivent être remappées sur votre hôte source, vous devez préparer l'hôte source à la phase de mise en service. Si vos LUN clustered Data ONTAP doivent rester mappées sur l'hôte de test, aucune étape supplémentaire n'est requise sur l'hôte de test.
