---
permalink: san-host/task_testing_luns_with_file_systems_on_lvm_devices_before_cutover_phase.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, lun, file, system, lvm, devices, cutover, phase 
summary: 'Si vous utilisez l"outil 7-mode transition Tool \(7MTT\) 2.2 ou une version ultérieure et Data ONTAP 8.3.2 ou une version ultérieure pour effectuer une transition basée sur la copie de votre hôte Red Hat Enterprise Linux \(RHEL\), vous pouvez tester vos LUN clustered Data ONTAP migrées avec des systèmes de fichiers sur des périphériques LVM avant la phase de mise en service. Pendant le test, l"hôte source peut continuer à exécuter les E/S sur les LUN 7-mode source.' 
---
= Test des LUN avec des systèmes de fichiers sur des périphériques LVM avant la phase de mise en service des transitions basées sur la copie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez l'outil 7-mode transition Tool (7MTT) 2.2 ou une version ultérieure et Data ONTAP 8.3.2 ou une version ultérieure pour effectuer une transition basée sur la copie de votre hôte Red Hat Enterprise Linux (RHEL), vous pouvez tester vos LUN clustered Data ONTAP migrées avec des systèmes de fichiers sur vos périphériques LVM avant la phase de mise en service. Pendant le test, l'hôte source peut continuer à exécuter les E/S sur les LUN 7-mode source.

* Vos nouvelles LUN clustered Data ONTAP doivent être mappées sur l'hôte de test.
* Vos LUN doivent être prêtes à la transition.


Vous devez maintenir la parité matérielle entre l'hôte de test et l'hôte source et effectuer les étapes suivantes sur l'hôte de test.

Vos LUN clustered Data ONTAP sont en mode lecture/écriture pendant le test. Ils se convertissent en mode lecture seule une fois le test terminé et que vous préparez la phase de mise en service.

En mode test, vous ne désactivez pas ou n'exportez pas le groupe de volumes. C'est pourquoi des erreurs de système de fichiers peuvent s'afficher lors du montage des volumes logiques sur l'hôte de test.

.Étapes
. Une fois la copie des données de base terminée, sélectionnez *Test mode* dans l'interface utilisateur 7MTT.
. Dans l'interface utilisateur 7MTT, cliquez sur *Apply Configuration*.
. Sur l'hôte de test, découvrez vos nouveaux LUN clustered Data ONTAP :
+
`*rescan-scsi-bus.sh*`

. Vérifiez que vos nouvelles LUN clustered Data ONTAP ont été découvertes :
+
`*sanlun lun show*`

. Configurez des périphériques DMMP pour vos LUN clustered Data ONTAP :
+
`*multipath*`

. Obtenez l'ID de descripteur de périphérique pour les LUN clustered Data ONTAP :
+
`*multipath -ll*`

+
Voici un exemple d'ID de poignée de dispositif : « 3600a09804d532d79565d47617679764d » »

. Identifiez les périphériques DMMP utilisés par le LVM :
+
`*pvscan*`

+
3600a09804d532d79565d776176797655 est un exemple de dispositif DMMP utilisé par le LVM.

. Identifiez le groupe de volumes :
+
`*vgscan*`

. Identification du volume logique :
+
`*lvscan*`

. Activez les volumes logiques : *
`*vgchange -ay _volume_group_*`
. Vérifiez l'état du volume logique : *
`*lvdisplay*`
+
Le `LV Status` la colonne du résultat doit s'afficher disponible.

. Déterminez si une entrée de point de montage pour le volume logique existe dans l' `/etc/fstab` fichier sur l'hôte source.
+
Dans l'exemple suivant, volume logique `/dev/mapper/vg_7MTT-lv1` s'affiche dans le `/etc/fstab` fichier :

+
[listing]
----
# /etc/fstab
...
tmpfs   /dev/shm  tmpfs   defaults        0 0
devpts  /dev/pts  devpts  gid=5, mode=620 0 0
sysfs   /sys      sysfs   defaults        0 0
proc    /proc     proc    defaults        0 0
/dev/mapper/vg_7MTT-lv1 /7MTT  ext4  defaults 0	0
----
. Si une entrée de point de montage pour le volume logique existe dans le `/etc/fstab` sur l'hôte source, modifiez manuellement `/etc/fstab` fichier sur l'hôte de test pour ajouter l'entrée du point de montage.
. Monter le point de montage :
+
`*mount -a*`

. Vérifiez que les points de montage sont montés :
+
`*mount*`

. Effectuez les tests selon les besoins.
. Une fois le test terminé, arrêtez l'hôte :
+
`*shutdown -h -t0 now*`

. Dans l'interface utilisateur 7MTT, cliquez sur *Finish Testing*.


Si vos LUN clustered Data ONTAP doivent être remappées sur votre hôte source, vous devez préparer l'hôte source à la phase de mise en service. Si vos LUN clustered Data ONTAP doivent rester mappées sur l'hôte de test, aucune étape supplémentaire n'est requise sur l'hôte de test.

*Informations connexes*

xref:task_gathering_pretransition_information_from_inventory_assessment_workbook.adoc[Collecte des informations de pré-transition à partir du manuel d'évaluation de l'inventaire]

xref:task_preparing_for_cutover_when_transitioning_linux_host_file_systems_on_lvm_devices.adoc[Préparation de la phase de mise en service lors de la transition de systèmes de fichiers hôtes Linux sur des périphériques LVM]
