---
permalink: san-host/task_preparing_for_cutover_when_transitioning_linux_host_dmmp_device_without_file_system.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, cutover, linux, dmmp, device, host 
summary: 'Si vous faites la transition d"un périphérique DMMP sans système de fichiers depuis un hôte Linux, vous devez effectuer plusieurs étapes avant de passer à la phase de mise en service.' 
---
= Préparation de la mise en service lors de la transition d'un périphérique DMMP hôte Linux sans système de fichiers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous faites la transition d'un périphérique DMMP sans système de fichiers depuis un hôte Linux, vous devez effectuer plusieurs étapes avant de passer à la phase de mise en service.

Pour les configurations FC, vous devez disposer d'une connectivité et d'une segmentation de la structure vers les contrôleurs clustered Data ONTAP.

Pour les configurations iSCSI, vos sessions iSCSI doivent être découvertes et connectées à vos contrôleurs clustered Data ONTAP.

* Pour les transitions basées sur les copies, effectuez ces étapes avant de lancer l'opération de mise en service du stockage dans l'outil de transition 7-mode (7MTT).
* Pour les transitions sans copie, effectuez ces étapes avant de lancer l'opération Export & halt 7-mode dans 7MTT.


.Étapes
. Arrêtez les E/S aux points de montage.
. Arrêtez les applications qui accèdent aux LUN en fonction des recommandations du fournisseur de l'application.
. Rincez le périphérique DMMP ou l'alias du LUN 7-mode :
+
`*multipath -f _device_name_*`

+
Si nécessaire, vous pouvez obtenir le nom de périphérique DMMP à partir de la colonne *ID de périphérique OS* sous l'onglet LUN hôte SAN dans le _Workbook d'évaluation d'inventaire_.


