---
permalink: copy-based/task_aborting_a_subproject.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, abort, project 
summary: 'Vous pouvez abandonner un projet en cours d"exécution, par exemple lorsque les performances du contrôleur ou du cluster sont affectées. Vous pouvez abandonner un projet en cours d"exécution à partir du tableau de bord.' 
---
= Abandon d'un projet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez abandonner un projet en cours d'exécution, par exemple lorsque les performances du contrôleur ou du cluster sont affectées. Vous pouvez abandonner un projet en cours d'exécution à partir du tableau de bord.

Vous devez tenir compte des éléments suivants avant d'abandonner les projets qui permettent la transition des volumes avec des relations SnapMirror :

* Si les deux projets ont été lancés, l'abandon d'un projet entraîne l'abandon du projet associé.
+
Par exemple, si vous annulez un projet principal, le projet secondaire est également abandonné.

* Si l'opération d'abandon échoue sur le projet en cours, le projet associé n'est pas interrompu.
* Si un seul projet actif est abandonné, l'opération de démarrage sur le projet associé échoue.
* Lorsque vous abandonnez un projet principal, l'opération de copie du volume primaire 7-mode vers le volume secondaire ONTAP n'est pas abandonnée.
+
Seule la copie du volume primaire 7-mode vers le volume primaire ONTAP correspondant est abandonnée.




NOTE: Si le projet 7-mode est interrompu, la seule option est de supprimer le projet. Il n'est pas possible de reprendre ou de redémarrer le projet après son abandon.

.Étapes
. Dans le tableau de bord, sélectionnez le projet que vous souhaitez abandonner.
. Cliquez sur *abandonner*.
. Depuis le cluster, supprimez les volumes ONTAP créés dans le cadre de la transition.
. À partir du système 7-mode, libérer les relations SnapMirror avec les volumes ONTAP.
. Si vous interrompez une relation SnapMirror volume, vous devez effectuer les opérations suivantes :
+
.. Rompez et supprimez la relation SnapMirror entre les volumes primaires 7-mode et les volumes secondaires ONTAP.
.. À partir du système 7-mode principal, relâcher les relations SnapMirror avec les volumes secondaires ONTAP.




http://["Commandes ONTAP 9"]

https://["Data ONTAP 8. 2 commandes : référence des pages manuelles pour 7-mode, volume 1"]
