---
permalink: copy-based/task_starting_data_copy_for_a_transition_session.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, start, data, copy, project 
summary: Vous pouvez lancer une copie des données des volumes 7-mode vers des volumes ONTAP pour un transfert de base. Le transfert de base démarre lorsque les planifications de copie de données configurées dans un projet deviennent actives. Une fois le transfert de base terminé, les volumes ONTAP sont mis à jour régulièrement, selon la planification des copies de données. 
---
= Démarrage de la copie des données d'un projet de transition
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez lancer une copie des données des volumes 7-mode vers des volumes ONTAP pour un transfert de base. Le transfert de base démarre lorsque les planifications de copie de données configurées dans un projet deviennent actives. Une fois le transfert de base terminé, les volumes ONTAP sont mis à jour régulièrement, selon la planification des copies de données.

* Vous devez avoir exécuté une vérification préalable sur le projet et résolu toutes les erreurs.
* Vous devez avoir configuré un réseau dédié, à large bande passante et à faible latence entre les systèmes source et de destination pour le transfert des données.
+

NOTE: Les chemins d'accès multiples de SnapMirror peuvent être utilisés pour équilibrer la charge du transfert de données entre les deux chemins.

* Un planning de copie des données doit être configuré pour la session.


Si vous effectuez une transition vers un SVM existant, les volumes sont créés au cours de cette opération. Si vous effectuez une transition vers un nouveau SVM, le SVM et ses volumes sont créés au cours de cette opération.

Les relations SnapMirror sont créées entre les volumes 7-mode et ONTAP.

.Étapes
. Lancer la copie des données :
+
`*transition start -p _project_name_*`

+
Si l'opération de démarrage échoue et que la copie des données n'est pas démarrée, vous devez résoudre les problèmes et exécuter le `transition start` commande de nouveau.

+
[listing]
----
7-Mode Transition Tool>transition start -p project_finance

[1/17 ] Project status checks                                      [      Ok       ]
[2/17 ] Validating 7-Mode system information                       [      Ok       ]
[3/17 ] Validating 7-Mode volumes information                      [      Ok       ]
[4/17 ] Validating Cluster-Mode system information                 [      Ok       ]
[5/17 ] Validating Cluster-Mode volume information                 [      Ok       ]
[6/17 ] Validating LIF information                                 [ Notifications ]
[7/17 ] WAFL prechecks                                             [      Ok       ]
[8/17 ] UNIX users and groups prechecks                            [   Warnings    ]
[9/17 ] SnapMirror prechecks                                       [ Notifications ]
[10/17] NFS prechecks                                              [   Warnings    ]
[11/17] Networking prechecks                                       [ Notifications ]
[12/17] CIFS prechecks                                             [   Warnings    ]
[13/17] Name services prechecks                                    [   Warnings    ]
[14/17] SAN prechecks                                              [      Ok       ]
[15/17] Creating Cluster-Mode volumes                              [      Ok       ]
[16/17] Establishing SnapMirror relationships between the 7-Mode and Cluster-Mode volumes                                                            [      Ok       ]
[17/17] Initializing SnapMirror relationships between the 7-Mode and Cluster-Mode volumes                                                            [      Ok       ]

Operation summary:
------------------
The 'start' operation is completed with warnings and notifications.

 0  Errors - No action required
22  Warnings - Need your attention!
16  Notifications - Please review
102  Informational messages

Do you want to see a detailed report {yes, no} [yes]:

22 Warnings:
------------
20362: Checking whether 7-Mode UNIX groups' names are in use in the Vserver 'vs2'.  [    Warning    ]
  > The following 7-Mode UNIX groups' names are already in use in the Vserver 'vs2'.
  > AFFECTED-OBJECTS: { daemon }

20372: Checking whether 7-Mode UNIX groups' ids are in use in the Vserver 'vs2'.    [    Warning    ]
  > The following 7-Mode UNIX groups' ids are already in use in the Vserver 'vs2'.
  > AFFECTED-OBJECTS: { daemon }
----
+
Le projet passe à l'état copie-ligne de base. Une fois le transfert de base terminé, le projet passe à l'état copie-mise à jour.


