---
permalink: copy-based/task_running_precheck_on_a_session.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, run, prechecks 
summary: 'Après avoir créé une session de transition, vous pouvez valider la session pour vérifier si l"environnement 7-mode peut être mis à niveau à l"aide de la commande « contrôle préalable de transition ». Vous pouvez vérifier la compatibilité entre le système de stockage 7-mode et le SVM pour des facteurs tels que les fonctionnalités et les paramètres de sécurité.' 
---
= Exécution de contrôles préalables
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir créé une session de transition, vous pourrez valider cette session pour vérifier si l'environnement 7-mode peut être transféré à l'aide du `transition precheck` commande. Vous pouvez vérifier la compatibilité entre le système de stockage 7-mode et le SVM pour des facteurs tels que les fonctionnalités et les paramètres de sécurité.

La session de transition doit être à l'état de préparation.

Le `transition cbt precheck` commande génère un rapport détaillé de messages d'erreur. Selon l'impact du problème sur le processus de transition, les problèmes identifiés dans le rapport se voient affecter des niveaux de sévérité différents. Étant donné que certaines erreurs peuvent entraver la transition, vous devez effectuer des actions correctives pour les erreurs et les avertissements. Avant de procéder à la transition, vous devez également vérifier l'impact des messages indiquant d'autres niveaux de sévérité.

.Étapes
. Vérifiez la compatibilité pour la transition :
+
`*transition cbt precheck -p _project_name_*`

+
[listing]
----
7-Mode Transition Tool>transition cbt precheck -p project_finance

[1/14 ] Project status checks                                                  [    Errors     ]

Operation summary:
------------------
The 'precheck' operation on the project 'project_finance' has failed.

 1  Errors - Failed!

Do you want to see a detailed report {yes, no} [yes]:

1 Errors:
---------
90202: Checking whether any of the 7-Mode volumes are in 'offline' state.                              [     Error     ]
  > Following volumes are in 'offline' state.
  > CORRECTIVE-ACTION: Bring offline volumes online by using the following command: 'vol online
  > <volume_name>'.
  > AFFECTED-OBJECTS: { vol2 }

Next suggested steps:
---------------------
1. Review the 'precheck' operation results, fix all blocking errors and run the 'precheck' operation again.
2. Use the 'transition job-results -j 6e33e0a7-bb36-49df-91f3-2e52cbfa3074' command to see the results of this
operation.

Ran precheck for project 'project_finance'.
----


Vous devez résoudre toutes les erreurs susceptibles de provoquer des problèmes de transition avant de lancer la copie des données à partir des volumes 7-mode.
