---
permalink: copy-based/task_transitioning_volumes_by_excluding_a_subset_of_configurations.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, customize, cli 
summary: 'Par défaut, toutes les configurations 7-mode sont migrées vers ONTAP. Vous pouvez choisir d"exclure de la transition une partie ou toutes les configurations de volume, NFS, CIFS, SAN et de services de noms à l"aide de l"interface de ligne de commande 7-mode transition Tool. Vous pouvez également choisir de consolider les règles d"export NFS 7-mode et les planifications Snapshot, et de réutiliser une export policy NFS existante et une policy Snapshot sur le SVM cible.' 
---
= Personnalisation de la transition de configurations 7-mode à l'aide de l'interface de ligne de commandes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Par défaut, toutes les configurations 7-mode sont migrées vers ONTAP. Vous pouvez choisir d'exclure de la transition une partie ou toutes les configurations de volume, NFS, CIFS, SAN et de services de noms à l'aide de l'interface de ligne de commande 7-mode transition Tool. Vous pouvez également choisir de consolider les règles d'export NFS 7-mode et les planifications Snapshot, et de réutiliser une export policy NFS existante et une policy Snapshot sur le SVM cible.

Vous devez effectuer cette tâche avant d'appliquer la configuration, après laquelle toute modification sera ignorée.

7-mode transition Tool n'effectue pas de contrôles préalables pour la configuration exclue.

Par défaut, toutes les configurations 7-mode sont sélectionnées pour la transition.

Il est préférable d'exécuter les contrôles préalables avec toutes les configurations, puis d'exclure une ou plusieurs configurations lors de l'exécution ultérieure des contrôles préalables. Cela vous aide à comprendre quelles configurations sont exclues de la transition et quels contrôles préalables sont ignorés par la suite.

.Étapes
* Exclure et vérifier les configurations :
+
.. Exclure les configurations : +
`*transition cbt property-set -p _project_name_ -n _config_property_name_ -v true*`
+
`_config_property_name_` est la configuration que vous souhaitez exclure.

+
xref:reference_configurations_that_can_be_excluded.adoc[Les configurations peuvent être exclues de la transition]

.. Vérifiez la valeur de la propriété définie pour l'exclusion de la configuration :
+
`*transition cbt property-get -p _project_name_ -n _config_property_name_*`



* Consolidation des règles d'exportation NFS pour la transition :
+
** Consolidation des règles d'exportation NFS 7-mode similaires en une seule export policy dans clustered Data ONTAP, qui peut ensuite être appliquée au volume transféré ou au qtree : +
`*transition cbt property-set -p _project_name_ -n _nfs-consolidate-similiar-7mode-exports_ -v true*`
+
Si le `nfs-consolidate-similiar-7mode-exports` la propriété est définie sur `false`, L'outil 7-mode transition Tool crée une nouvelle export policy NFS dans ONTAP pour chaque règle d'exportation NFS 7-mode.

** Réutilisez une export policy NFS existante sur le SVM qui correspond à la export policy qui sera créée par l'outil, qui peut être appliquée aux volumes transférés ou aux qtrees: +
`*transition cbt property-set -p _project_name_ -n _nfs-reuse-matching-svm-export-policies_ -v true*`


* Consolider les plannings Snapshot pour la transition :
+
** Consolidation des planifications Snapshot 7-mode similaires avec une seule règle Snapshot de ONTAP, qui peut ensuite être appliquée au volume transféré : +
`*transition cbt property-set -p _project_name_ -n _consolidate-similar-7mode-snapshot-policies_ -v true*`
+
Si le `consolidate-similar-7mode-snapshot-policies` La propriété est définie sur false, l'outil 7-mode transition Tool crée une nouvelle règle Snapshot dans ONTAP pour chaque planification Snapshot.

** Réutilisez une politique Snapshot existante sur la SVM qui correspond à la politique Snapshot qui sera créée par l'outil, qui peut être appliquée aux volumes transférés : +
`*transition cbt property-set -p _project_name_ -n _reuse-matching-svm-snapshot-policies_ -v true*`



