---
settings:
  name: ONTAP 7-Mode Transition
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es
sidebar:
  entries:
  - title: Transition depuis la version 7-mode
    url: "/index.html"
  - title: Notes de version
    url: "/releasenotes.html"
  - section: command-map
  - section: install-admin
  - section: copy-based
  - section: copy-free
  - section: inventory-collect
  - section: snapmirror
  - section: san-host
  - title: Mentions légales
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Quoi de neuf
      summary: Découvrez les nouveautés de la dernière version de l'outil de transition
        7-mode
      url: releasenotes.html
    - title: Installer l'outil de transition 7-mode
      summary: Découvrez comment installer l'outil sous Microsoft Windows ou Linux
      url: "/install-admin/concept_transition_to_clustered_ontap_using_7mtt.html"
    - title: Collectez les données nécessaires pour la transition
      summary: Découvrez comment recueillir des informations essentielles à votre
        transition
      url: "/inventory-collect/concept_collecting_host_and_storage_inventory_information_for_transition_assessment.html"
  - title: Mappage de commandes pour les administrateurs 7-mode
    links:
    - title: Comment les commandes 7-mode s'associent aux commandes ONTAP
      summary: Trouver les équivalents ONTAP des commandes 7-mode
      url: "/command-map/reference_how_7_mode_commands_map_to_clustered_ontap_commands.html"
    - title: Comment les options 7-mode s'associent aux commandes ONTAP
      summary: Découvrez comment les options 7-mode s'associent aux paramètres de
        commande ONTAP
      url: "/command-map/reference_how_7_mode_options_map_to_clustered_ontap_commands.html"
    - title: Comment les fichiers de configuration 7-mode s'associent aux commandes
        ONTAP
      summary: Découvrez comment les fichiers de configuration 7-mode sont mappées
        aux commandes de configuration ONTAP
      url: "/command-map/reference_how_7_mode_configuration_files_map_to_clustered_ontap_commands.html"
  - title: Modes de transition
    links:
    - title: Transition basée sur la copie
      summary: Utilisez cet outil pour effectuer une transition basée sur les copies
        de 7-mode vers ONTAP
      url: "/copy-based/concept_copy_based_transition_workflow.html"
    - title: La transition sans copie
      summary: Utilisez cet outil pour effectuer une transition sans copie de 7-mode
        vers ONTAP
      url: "/copy-free/task_copy_free_transition_workflow.html"
    - title: Transition des données à l'aide de SnapMirror
      summary: Apprenez à migrer des données de 7-mode vers ONTAP à l'aide des commandes
        SnapMirror
      url: "/snapmirror/task_transitioning_7_mode_volumes_using_snapmirror.html"
  - title: Transition et résolution des problèmes liés aux hôtes SAN
    links:
    - title: VMware ESXi
      summary: Comprendre les exigences de pré et post-transition des hôtes VMware
        ESXi
      url: "/san-host/concept_vmware_esxi_host_remediation.html"
    - title: Red Hat Enterprise Linux
      summary: Comprendre les exigences préalables et postérieures à la transition
        pour les hôtes Red Hat Enterprise Linux
      url: "/san-host/concept_linux_host_remediation.html"
    - title: Répertoires de base
      summary: Comprendre les étapes de pré et post-transition pour les hôtes Microsoft
        Windows
      url: "/san-host/concept_windows_host_remediation.html"
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: Toute la documentation sur les produits ONTAP
