---
settings:
  name: ONTAP 7-Mode Transition
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Transition depuis la version 7-mode
    url: "/index.html"
  - title: Notes de version
    url: "/releasenotes.html"
  - section: command-map
  - section: install-admin
  - section: copy-based
  - section: copy-free
  - section: inventory-collect
  - section: snapmirror
  - section: san-host
  - title: Mentions légales
    url: "/reference_legal_notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
