---
permalink: inventory-collect/task_collecting_inventory_and_generating_inventory_report.html 
sidebar: sidebar 
keywords: ontap, 7, mode, collect, inventory, generating, inventory, report, transition 
summary: 'Vous pouvez collecter des informations sur les systèmes Data ONTAP \(systèmes 7-mode et nœuds du cluster\), les commutateurs, les hôtes et les applications hôtes. Grâce à ces informations, vous pouvez générer un rapport d"inventaire qui contient des informations détaillées sur les systèmes 7-mode, les hôtes et les applications hôtes pour l"évaluation de la transition.' 
---
= Collecte du stock et génération du rapport d'inventaire
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez collecter des informations sur les systèmes Data ONTAP (systèmes 7-mode et nœuds du cluster), les commutateurs, les hôtes et les applications hôtes. Grâce à ces informations, vous pouvez générer un rapport d'inventaire qui contient des informations détaillées sur les systèmes 7-mode, les hôtes et les applications hôtes pour l'évaluation de la transition.

* Vous devez avoir téléchargé le `ict.exe` Fichier depuis le site de support NetApp.
* Vous devez disposer du nom d'utilisateur, du mot de passe et des adresses IP des systèmes de stockage et des hôtes pour lesquels le rapport d'inventaire est requis.
* Le nom d'utilisateur du système de stockage et des hôtes doit disposer de privilèges suffisants pour exécuter les commandes.
* Si vous ajoutez plusieurs systèmes pour la collection d'inventaire, vous devez avoir créé un fichier texte encodé au format ASCII ou UTF-8 et contenant les détails du système, un système par ligne.
+
Chaque détail du système doit être au format suivant :

+
`(ontap|windows|vmware|linux|cisco|brocade)://[(_domain_user__\\__user__):_[password]@](host_name|ip)__`

+
Si vous fournissez `*` en tant que mot de passe, vous êtes invité à saisir le mot de passe sur la ligne de commande.

* Toutes les fonctionnalités doivent être configurées et leurs licences doivent être activées pour que le classeur puisse contenir les informations d'inventaire relatives aux fonctions.
* Toutes les configurations du système de stockage, telles que les noms de partage CIFS, les noms d'utilisateur et les noms de groupe, doivent être au format UTF-8.
* Pour le plan de zone FC, les systèmes 7-mode et les hôtes doivent être connectés au commutateur.
+
Le cluster peut être connecté au même commutateur que le système 7-mode ou à un nouveau commutateur dans la même structure.



L'outil Inventory Collect Tool peut collecter des informations de configuration à partir d'un maximum de quatre contrôleurs et 20 hôtes simultanément. Cependant, pour les configurations mises à l'échelle avec quotas, qtrees, exportations ou utilisateurs et groupes UNIX, la génération du rapport d'inventaire peut prendre beaucoup plus de temps.


NOTE: Vous devez éviter d'effectuer des opérations de collecte des stocks sur des contrôleurs de stockage actifs pendant les heures de pointe.

. À l'invite de commande Windows, accédez au chemin d'accès où l'outil de collecte d'inventaire est téléchargé.
. Générez le rapport d'inventaire en exécutant le `ict` Commande avec l'adresse IP et les identifiants du système :
+
|===
| Vous souhaitez fournir des informations... | Saisissez la commande suivante... 


 a| 
Pour chaque système à l'aide de l'interface de ligne de commandes
 a| 
`*ict --cmd collect --output _filename_ (ontap|windows|vmware|linux|cisco|brcade)://[(_user_|_domain_user_)[:(_password_|***)]@_hostname_) ...*

** `_filename_` est le nom que vous souhaitez fournir pour le rapport d'inventaire.
** `ontap|windows|vmware|linux` est le type de système.
+
Par exemple, pour un système de stockage 7-mode, le type de système est ONTAP et pour un hôte Linux, le type de système est linux.

** `cisco|brocade` Les commutateurs FC pris en charge sont-ils pris en charge ?
** `_user|domain_user_` et `_password_` sont les informations d'identification du système.
+
Si le contrôleur n'a pas de mot de passe, vous pouvez saisir les caractères `\"\"` comme mot de passe.

** `_hostname_` Est l'adresse IP ou le nom d'hôte du contrôleur, de l'hôte ou du commutateur.




 a| 
Pour plusieurs systèmes dans un fichier texte
 a| 
`*ict --cmd collect --output _filename_ --input _credentials_file.txt_*`

`_credentials_file.txt_` est le fichier texte qui contient les détails du système et les informations d'identification pour plusieurs systèmes :

** Seuls les fichiers texte encodés au format ASCII sont pris en charge.
** Si vous fournissez `*` en tant que mot de passe, vous êtes invité à saisir le mot de passe sur la ligne de commande.
** Si le contrôleur ne possède pas de mot de passe, vous pouvez entrer `""` comme mot de passe.


|===
+

NOTE: Si votre système de stockage exécute Windows 7 ou une version ultérieure et que vous disposez de privilèges limités sur le dossier dans lequel le fichier XML de sortie du rapport d'inventaire sera stocké, les fichiers de sortie sont automatiquement stockés dans le `VirtualStore` le répertoire et l'application s'exécutent normalement.

+
Le rapport d'inventaire est créé pour un système de stockage et un hôte Linux. Les rapports générés sont `collected_data.xml` et `collected_data_InventoryWorkbook.xml`:

+
[listing]
----
ict --cmd collect --output collected_data ontap://root:test123@hostname1 linux://root@hostname2
----
+
Le temps estimé nécessaire à la collecte des informations d'inventaire par contrôleur s'affiche.

+
Le classeur d'inventaire et le rapport d'inventaire sont générés au format XML.

. Affichez le classeur d'inventaire dans Microsoft Excel à l'aide de Microsoft Office 2007 ou versions ultérieures.


Vous êtes prêt à importer le rapport XML d'inventaire dans l'outil 7-mode transition Tool afin d'évaluer les fonctionnalités du contrôleur et des hôtes 7-mode, et d'identifier comment les fonctionnalités fonctionnent dans la version de clustered Data ONTAP sélectionnée pour la transition.
