---
permalink: copy-free/concept_restrictions_for_copy_free_transition.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, aggregates, volumes, restrictions 
summary: Vous devez tenir compte de certaines restrictions relatives à la transition des agrégats et volumes 7-mode. Certaines restrictions sont dues à des fonctions qui ne sont pas prises en charge dans ONTAP. Pour certaines restrictions, vous pouvez effectuer une action corrective qui vous permet de poursuivre la transition. 
---
= Restrictions pour la transition des agrégats et volumes 7-mode
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez tenir compte de certaines restrictions relatives à la transition des agrégats et volumes 7-mode. Certaines restrictions sont dues à des fonctions qui ne sont pas prises en charge dans ONTAP. Pour certaines restrictions, vous pouvez effectuer une action corrective qui vous permet de poursuivre la transition.



== Types de volume

Les types de volumes suivants ne sont pas pris en charge pour la transition :

* Volumes traditionnels
+
Vous pouvez utiliser des méthodes de transition basées sur hôte pour effectuer la transition de volumes traditionnels.

+
https://www.netapp.com/pdf.html?item=/media/19510-tr-4052.pdf["Rapport technique de NetApp 4052 : une transition réussie vers clustered Data ONTAP (Data ONTAP 8.2.x et 8.3)"^]

* Volumes SnapLock
+
La transition de volumes SnapLock est prise en charge pour toutes les dernières versions d'ONTAP.

* Volumes FlexCache




== État de l'agrégat et du volume

La transition est bloquée si l'un des agrégats 7-mode et volumes sélectionnés pour la transition sont dans l'un des États suivants :

* Hors ligne
* Limitée
* Incohérent (`wafl inconsistent`)




== Volumes FlexClone

La hiérarchie des clones et l'efficacité du stockage sont préservées durant la transition sans copie. Cependant, vous devez vous assurer que le volume FlexVol parent et l'ensemble de ses volumes FlexClone appartiennent à la même unité vFiler. Si les volumes FlexClone se trouvent dans différentes unités vFiler du volume parent, vous devez choisir l'une des actions suivantes :

* Déplacez les volumes FlexClone vers l'unité vFiler propriétaire du volume FlexVol parent.
* Séparez les clones du volume FlexClone parent, puis effectuez la transition de ces volumes en tant que volumes FlexVol.




== Volume avec qtrees appartenant à une autre unité vFiler

Vous ne pouvez pas effectuer la transition de volumes avec des qtrees dont les qtrees sont la propriété d'une unité vFiler différente de celle du volume. Avant la transition, vous devez vous assurer que chaque volume et tous ses qtrees appartiennent à la même unité vFiler en effectuant l'une des actions suivantes :

* Déplacez les qtrees vers l'unité vFiler propriétaire du volume.
* Supprimez les qtrees.




== Paramètre de conversion du nom d'inode vers le nom parent

Les traductions du nom d'inode vers le nom parent doivent être activées sur chaque volume. Vous pouvez activer les conversions de chemin d'accès du parent en désactivant l'option no_i2p :

`*vol options _vol_name_ no_i2p off*`

Il n'est pas nécessaire d'attendre la fin de l'acquisition i2p, et vous pouvez poursuivre la préparation de la transition.
