---
permalink: copy-free/concept_requirements_for_copy_free_transition.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, requirements 
summary: Vous devez tenir compte des exigences relatives aux systèmes 7-mode, aux clusters, aux versions ONTAP et aux tiroirs disques pour une transition sans copie. 
---
= Conditions requises pour une transition sans copie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez tenir compte des exigences relatives aux systèmes 7-mode, aux clusters, aux versions ONTAP et aux tiroirs disques pour une transition sans copie.

N'oubliez pas de consulter la version actuelle de 7-mode transition Tool _Release Notes_ pour obtenir les dernières informations sur les versions cibles prises en charge et les problèmes connus.

link:https://docs.netapp.com/us-en/ontap-7mode-transition/releasenotes.html["Notes de version de l'outil 7-mode transition Tool"]

* *Modèles de plate-forme*
+
La transition sans copie est prise en charge uniquement sur les systèmes FAS de milieu et de haut de gamme et sur les systèmes IBM N series. Le https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"] Dispose des dernières informations sur les plateformes prises en charge pour les systèmes 7-mode et les nœuds de cluster cibles.

* *Data ONTAP dans les systèmes source 7-mode*
+
Pour obtenir la liste des versions de 7-mode prises en charge pour la migration par l'outil 7-mode transition Tool, consultez la https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"]

* *Systèmes cibles ONTAP*
+
L'outil de transition 7-mode version 3.3.1 prend en charge la transition vers les versions ONTAP suivantes grâce à la méthode sans copie :

+
** ONTAP 9.4 et versions antérieures de ONTAP 9
** Clustered Data ONTAP 8.3.2 et versions ultérieures 8.x *Remarque :* vous ne pouvez pas utiliser l'outil 7-mode transition Tool pour migrer vers ONTAP 9.5 ou version ultérieure en utilisant la méthode sans copie. Pour ce faire, vous devez d'abord passer à ONTAP 9.4 avec l'outil de transition 7-mode 3.3.1, puis mettre à niveau votre cluster vers ONTAP 9.5 ou version ultérieure. 7-mode transition Tool 3.3.2 ne prend pas en charge les transitions sans copie.


* *Configuration HA*
+
Les contrôleurs 7-mode et les nœuds de cluster cibles doivent se trouver dans une configuration HA. Les paires HA doivent être saines et aucun des nœuds ne peut être en mode basculement. Les contrôleurs autonomes ne sont pas pris en charge pour la transition sans copie.

* *Modèles de tiroirs disques*
+
Les modèles de tiroirs disques suivants sont pris en charge :

+
** DS4486
** DS4246
** DS4243
+

NOTE: Le modèle de tiroir disque DS4243 n'est pas pris en charge par ONTAP 9.2 et ONTAP 9.4. Ce modèle est pris en charge avec toutes les versions de correctif ONTAP 9.2 à partir de ONTAP 9.2P1 et de ONTAP 9.3. L'outil de transition 7-mode 3.3.1 prend en charge la transition avec le modèle de tiroir disque DS4243, pour une transition sans copie vers ONTAP 9.2P1 à ONTAP 9.3.

** DS2246
** DS14mk4 FC (non pris en charge dans ONTAP 9.0 et versions ultérieures)
** DS14mk2 AT (non pris en charge par ONTAP 9.0 et versions ultérieures)





NOTE: Le modèle de tiroir disque DS14mk2 FC n'est pas pris en charge.

* *Micrologiciel de disque*
+
Vous devez télécharger et installer le dernier pack de qualification de disques, firmware de disque, tiroir disque et firmware ACP sur les systèmes 7-mode et les nœuds de cluster cibles.

+
https://mysupport.netapp.com/NOW/download/tools/diskqual/["Téléchargements NetApp : pack de qualification des disques"]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Téléchargements NetApp : firmware de disque"]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Téléchargements NetApp : firmware des tiroirs disques"]

* *Outil de vérification du câblage*
+
Après avoir connecté les tiroirs disques 7-mode aux nœuds de cluster cible pendant la transition, vous devez utiliser Config Advisor pour vérifier le câblage.

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Téléchargement NetApp : Config Advisor"]


