---
permalink: copy-free/task_transitioning_primary_and_secondary_systems_of_a_snapmirror_relationship_in_parallel.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, primary, secondary, system, snapmirror, relationship, parallel 
summary: 'Vous pouvez effectuer la transition des paires HA principale et secondaire qui contiennent les volumes d"une relation SnapMirror 7-mode en parallèle. Vous devez ensuite configurer manuellement la relation de volume SnapMirror dans clustered Data ONTAP après la transition. La relation SnapMirror est conservée après la transition sans nécessiter de redéfinition de la base.' 
---
= Transition simultanée des systèmes primaires et secondaires dans une relation SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer la transition des paires HA principale et secondaire qui contiennent les volumes d'une relation SnapMirror 7-mode en parallèle. Vous devez ensuite configurer manuellement la relation de volume SnapMirror dans clustered Data ONTAP après la transition. La relation SnapMirror est conservée après la transition sans nécessiter de redéfinition de la base.

Vous devez avoir préparé les clusters source et destination pour la transition des relations SnapMirror.

xref:task_preparing_cluster_for_transitioning_volume_snapmirror_relationships.adoc[Préparation du cluster pour la transition de relations SnapMirror volume]

Vous devez effectuer la transition des paires haute disponibilité secondaires et primaires dans la même fenêtre de mise en service.

.Étapes
. Effectuez une transition sans copie des deux paires haute disponibilité qui contiennent les volumes primaires et secondaires de la relation SnapMirror volume 7-mode à partir de l'outil 7-mode.
+
Avant de passer à la paire 7-mode HA qui contient les volumes secondaires, aucune intervention manuelle n'est requise pour les relations SnapMirror 7-mode. Les volumes secondaires 7-mode sont donc transférés en tant que volumes en lecture seule vers ONTAP.

+
xref:task_performing_copy_free_transition_of_7_mode_aggregates.adoc[Transition d'agrégats 7-mode sans copie]

. Créer une relation SVM intercluster entre les SVM contenant les volumes primaires et secondaires ayant fait l'objet d'une transition
+
https://["Administration du système"]

. Créez une relation SnapMirror volume entre les volumes primaires et secondaires ayant fait l'objet d'une transition.
+
https://["Préparation rapide de la reprise après sinistre en volume"]

. Sur le volume de destination, faire une resynchronisation du volume source et du volume de destination de la relation SnapMirror :
+
`*snapmirror resync*`

+

IMPORTANT: Au moins une copie Snapshot commune doit exister entre les volumes source et de destination.

+
*Dépannage:* la resynchronisation SnapMirror échoue si la copie Snapshot commune a été créée dans une version de Data ONTAP antérieure à 8.1. Vous pouvez utiliser le `-fs-version` paramètre avec le `volume snapshot show` Commande au niveau de privilège avancé pour afficher la version dans laquelle la copie Snapshot a été créée. Si vous rencontrez ce problème, interrompre la relation SnapMirror et effectuer la resynchronisation.

. Surveiller l'état des transferts de données SnapMirror :
+
`*snapmirror show*`

+

IMPORTANT: Vous ne devez pas effectuer d'opération, par exemple le déplacement de volume ou l'arrêt de SnapMirror, sur les volumes source et de destination jusqu'à ce que la resynchronisation soit terminée. Assurez-vous que la resynchronisation ne s'interrompt pas et s'effectue correctement ; sinon, les volumes peuvent passer à un état incohérent.

. Engager la transition du projet secondaire, suivi du projet principal.
+
xref:task_committing_7_mode_aggregates_to_clustered_ontap_format.adoc[Validation du projet de transition sans copie]



*Informations connexes*

http://["Commandes ONTAP 9"]

https://["System Manager"]
