---
permalink: copy-free/task_preparing_cluster_for_transitioning_volume_snapmirror_relationships.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, prepare, cluster, snapmirror, relationship 
summary: Pour la transition de relations SnapMirror volume 7-mode, vous devez ajouter la licence SnapMirror aux clusters source et de destination. Vous devez également créer une relation entre les clusters entre les clusters auxquels sont transférés les volumes primaires et secondaires des relations SnapMirror et créer les planifications SnapMirror. 
---
= Préparation du cluster pour la transition de relations SnapMirror volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour la transition de relations SnapMirror volume 7-mode, vous devez ajouter la licence SnapMirror aux clusters source et de destination. Vous devez également créer une relation entre les clusters entre les clusters auxquels sont transférés les volumes primaires et secondaires des relations SnapMirror et créer les planifications SnapMirror.

Vous devez avoir enregistré les planifications SnapMirror définies dans le `/etc/snapmirror.conf` Fichier du système secondaire 7-mode.

.Étapes
. Ajoutez la licence SnapMirror sur les clusters source et de destination :
+
`*system license add _license_code_*`

. Depuis chaque cluster, créez la relation entre clusters.
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-clus-peer/home.html["Configuration cluster et SVM peering express"]

. Créer les planifications sur les SVM secondaires correspondant aux planifications dans le système secondaire 7-mode :
+
`*job schedule cron create*`



*Informations connexes*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Commandes ONTAP 9"]
