---
permalink: snapmirror/reference_7_mode_ontap_version_requirements_for_transitioning_volumes_using_snapmirror.html 
sidebar: sidebar 
keywords: ontap, 7, mode, version, transition, requirements, data, clustered 
summary: Nous vous recommandons de connaître les versions de Data ONTAP 7-mode prises en charge pour la transition vers clustered Data ONTAP 8.3 ou version ultérieure. 
---
= Conditions requises pour la version 7-mode
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nous vous recommandons de connaître les versions de Data ONTAP 7-mode prises en charge pour la transition vers clustered Data ONTAP 8.3 ou version ultérieure.

Si le système 7-mode ne compte que des agrégats et des volumes 64 bits, vous pouvez transférer des volumes depuis les systèmes qui exécutent les versions 7-mode suivantes vers clustered Data ONTAP 8.3 ou version ultérieure :

* Data ONTAP 8.0
* Data ONTAP 8.0.1
* Data ONTAP 8.0.2
* Data ONTAP 8.0.3
* Data ONTAP 8.0.4
* Data ONTAP 8.0.5
* Data ONTAP 8.1
* Data ONTAP 8.1.2
* Data ONTAP 8.1.3
* Data ONTAP 8.1.4
* Data ONTAP 8.2
* Data ONTAP 8.2.1
* Data ONTAP 8.2.2
* Data ONTAP 8.2.3
* Data ONTAP 8.2.4
* Data ONTAP 8.2.5


Si le système 7-mode exécute Data ONTAP 8.0.x, 8.1.x ou 8.2 et contient des agrégats ou des volumes 32 bits avec des copies Snapshot 32 bits, vous devez effectuer une mise à niveau vers la version 8.1.4 P4 ou 8.2.1. Après la mise à niveau, vous devez développer les agrégats 32 bits sur 64 bits, puis rechercher et supprimer toutes les données 32 bits.

Vous devez mettre à niveau les versions 7-mode suivantes vers Data ONTAP 8.1.4 P4 avant de migrer vers clustered Data ONTAP 8.3 ou version ultérieure :

* Data ONTAP 7.3.3
* Data ONTAP 7.3.4
* Data ONTAP 7.3.5
* Data ONTAP 7.3.6
* Data ONTAP 7.3.7

