---
permalink: snapmirror/task_transitioning_secondary_volume.html 
sidebar: sidebar 
keywords: ontap, 7, mode, transition, snapmirror, volume, secondary 
summary: 'Le transfert d"un volume secondaire implique la création d"une relation SnapMirror, la réalisation d"un transfert de base, la mise à jour incrémentielle et la configuration d"une relation SnapMirror entre le volume primaire 7-mode et le volume secondaire clustered Data ONTAP.' 
---
= Transfert d'un volume secondaire
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le transfert d'un volume secondaire implique la création d'une relation SnapMirror, la réalisation d'un transfert de base, la mise à jour incrémentielle et la configuration d'une relation SnapMirror entre le volume primaire 7-mode et le volume secondaire clustered Data ONTAP.

Le cluster secondaire et le serveur virtuel de stockage (SVM) doivent déjà être configurés.

.Étapes
. Copier les données du volume 7-mode vers le volume clustered Data ONTAP :
+
.. Utilisez le `snapmirror create` Commande avec le type de relation TDP pour créer une relation SnapMirror entre le système 7-mode et la SVM.
+
[listing]
----
sec_cluster::> snapmirror create -source-path sec_system:dst_7_vol -destination-path dst_vserver:dst_c_vol -type TDP
Operation succeeded: snapmirror create the relationship with destination dst_vserver:dst_c_vol.
----
.. Utilisez le `snapmirror initialize` pour démarrer le transfert de base.
+
[listing]
----
sec_cluster::> snapmirror initialize -destination-path dst_vserver:dst_c_vol
Operation is queued: snapmirror initialize of destination dst_vserver:dst_c_vol.
----
.. Selon que vous souhaitez mettre à jour le volume clustered Data ONTAP manuellement ou en configurant une planification SnapMirror, effectuez l'action appropriée :
+
|===
| Les fonctions que vous recherchez... | Alors... 


 a| 
Mettre à jour les transferts manuellement
 a| 
... Utilisez le `snapmirror update` commande.
+
[listing]
----
sec_cluster::> snapmirror update -destination-path dst_vserver:dst_c_vol
----
... Utilisez le `snapmirror show` commande permettant de contrôler l'état de la copie des données.
+
[listing]
----
sec_cluster::> snapmirror show -destination-path dst_vserver:dst_c_vol
                            Source Path: sec_system:dst_7_vol
                       Destination Path: dst_vserver:dst_c_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: -
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
           Number of Successful Updates: 1
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----
... Passez à l'étape 3.




 a| 
Effectuer des transferts de mise à jour planifiés
 a| 
... Utilisez le `job schedule cron create` commande pour créer un programme de transferts de mise à jour.
+
[listing]
----
sec_cluster::> job schedule cron create -name 15_minute_sched -minute 15
----
... Utilisez le `snapmirror modify` Commande permettant d'appliquer la planification à la relation SnapMirror.
+
[listing]
----
sec_cluster::> snapmirror modify -destination-path dst_vserver:dst_c_vol -schedule 15_minute_sched
----
... Utilisez le `snapmirror show` commande permettant de contrôler l'état de la copie des données.
+
[listing]
----
sec_cluster::> snapmirror show -destination-path dst_vserver:dst_c_vol
                            Source Path: sec_system:dst_7_vol
                       Destination Path: dst_vserver:dst_c_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: 15_minute_sched
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
           Number of Successful Updates: 1
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----


|===


. Si vous planifiez des transferts incrémentiels, effectuez les étapes suivantes lorsque vous êtes prêt à la mise en service :
+
.. Utilisez le `snapmirror quiesce` commande pour désactiver tous les futurs transferts de mise à jour.
+
[listing]
----
sec_cluster::> snapmirror quiesce -destination-path dst_vserver:dst_vol
----
.. Utilisez le `snapmirror modify` Commande permettant de supprimer la planification SnapMirror.
+
[listing]
----
sec_cluster::> snapmirror modify -destination-path dst_vserver:dst_vol -schedule ""
----
.. Si vous aviez suspendu les transferts SnapMirror plus tôt, utilisez `snapmirror resume` Commande pour activer les transferts SnapMirror.
+
[listing]
----
sec_cluster::> snapmirror resume -destination-path dst_vserver:dst_vol
----


. Attendez la fin des transferts courants entre les volumes 7-mode et les volumes clustered Data ONTAP, puis déconnectez l'accès des clients des volumes 7-mode pour démarrer la mise en service.
. Utilisez le `snapmirror update` Commande pour effectuer la dernière mise à jour des données vers le volume clustered Data ONTAP.
+
[listing]
----
sec_cluster::> snapmirror update -destination-path dst_vserver:dst_vol
Operation is queued: snapmirror update of destination dst_vserver:dst_vol.
----
. Utilisez le `snapmirror show` commande pour vérifier que le dernier transfert a réussi.
. Utilisez le `snapmirror break` Commande permettant d'interrompre la relation SnapMirror entre le volume secondaire 7-mode et le volume secondaire clustered Data ONTAP.
+
[listing]
----
sec_cluster::> snapmirror break -destination-path dst_vserver:dst_vol
[Job 60] Job succeeded: SnapMirror Break Succeeded
----
. Si vos volumes disposent de LUN configurées, utilisez le `lun transition 7-mode show` Commande permettant de vérifier que les LUN ont été migrées.
+
Vous pouvez également utiliser le `lun show` Contrôlez le volume clustered Data ONTAP pour afficher toutes les LUN qui ont été migrées avec succès.

. Utilisez le `snapmirror delete` Commande de suppression de la relation SnapMirror entre le volume secondaire 7-mode et le volume secondaire clustered Data ONTAP.
+
[listing]
----
sec_cluster::> snapmirror delete -destination-path dst_vserver:dst_vol
----
. Utilisez le `snapmirror release` Commande permettant de supprimer les informations relatives aux relations SnapMirror du système 7-mode.
+
[listing]
----
system7mode> snapmirror release dataVol20 vs1:dst_vol
----
. Établissez une relation de reprise après incident entre le volume primaire 7-mode et le volume secondaire clustered Data ONTAP :
+
.. Utilisez le `vserver peer transition create` Commande de créer une relation de SVM peer-to-peer entre le volume primaire 7-mode et le volume secondaire clustered Data ONTAP.
+
[listing]
----
sec_cluster::> vserver peer transition create -local-vserver dst_vserver -src-filer-name src_system
Transition peering created
----
.. Utilisez le `job schedule cron create` Commande permettant de créer un job planning correspondant à la planification configurée pour la relation SnapMirror 7-mode.
+
[listing]
----
sec_cluster::> job schedule cron create -name 15_minute_sched -minute 15
----
.. Utilisez le `snapmirror create` Commande permettant de créer une relation SnapMirror entre le volume primaire 7-mode et le volume secondaire clustered Data ONTAP.
+
[listing]
----
sec_cluster::> snapmirror create -source-path src_system:src_7_vol -destination-path dst_vserver:dst_c_vol -type TDP -schedule 15_minute_sched
Operation succeeded: snapmirror create the relationship with destination dst_vserver:dst_c_vol.
----
.. Utilisez le `snapmirror resync` Commande permettant de resynchroniser le volume secondaire clustered Data ONTAP.
+
Pour effectuer une resynchronisation réussie, une copie Snapshot 7-mode courante doit exister entre le volume primaire 7-mode et le volume secondaire clustered Data ONTAP.

+
[listing]
----
sec_cluster::> snapmirror  resync -destination-path dst_vserver:dst_c_vol
----
+
*** Si le cluster cible exécute Data ONTAP 8.3.2 ou une version ultérieure, vous devez créer les groupes initiateurs requis et mapper les LUN manuellement.
*** Si le cluster cible exécute Data ONTAP 8.3.1 ou une version antérieure, vous devez mapper les LUN secondaires manuellement après la mise en service du stockage des volumes primaires.
*** Il faut supprimer la relation entre les pairs SVM secondaire entre le système 7-mode et la SVM secondaire lorsque tous les volumes requis du système 7-mode sont transférés vers la SVM.
*** Vous devez supprimer la relation SnapMirror entre les systèmes primaires 7-mode et les systèmes secondaires 7-mode.






*Informations connexes*

xref:task_recovering_from_a_failed_lun_transition.adoc[Restauration suite à une transition de LUN ayant échoué]

xref:task_configuring_a_tcp_window_size_for_snapmirror_relationships.adoc[Configuration d'une taille de fenêtre TCP pour les relations SnapMirror]
